demo:
  phoneNumber:

twilio:
  accountSID:
  authToken:
  phoneNumber:

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/real-time-notification-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:real-time-notification-service}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:1}
      pool-name: ${SPRING_DATASOURCE_POOL_NAME:HikariPool}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}


pyroscope:
  server:
    address:
  auth:
    user:
    password:
server:
  port: 8081

services:
  user-store:
    url: http://localhost:8080