spring:
  profiles:
    active: prd
  application:
    name: real-time-incident-notification-service
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${INCIDENT_JDBC_URL:jdbc:postgresql://localhost:5432/real-time-notification-service}
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 5
      minimum-idle: 1
  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info
  server:
    port: 8081

twilio:
  accountSID:
  authToken:
  phoneNumber:


server:
  port: 8080

pyroscope:
  server:
    address: ${PYROSCOPE_SERVER_ADDRESS:pyroscope:4040}
  auth:
    user: ${PYROSCOPE_AUTH_USER:9999999}
    password: ${PYROSCOPE_AUTH_PASSWORD:glc_fff}