spring:
  application:
    name: real-time-incident-notification-service
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/real-time-notification-service}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:1}
      pool-name: ${SPRING_DATASOURCE_POOL_NAME:HikariPool}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework: INFO

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info
  server:
    port: 8081

twilio:
  accountSID: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}

pyroscope:
  server:
    address: ${PYROSCOPE_SERVER_ADDRESS}
  auth:
    user: ${PYROSCOPE_AUTH_USER}
    password: ${PYROSCOPE_AUTH_PASSWORD}

demo:
  phoneNumber: ${DEMO_PHONE_NUMBER}

services:
  user-store:
    url: ${USER_STORE_URL:http://localhost:8080}